### ISSUE TITLE
Remove UserProfile in favor of User type

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/mattermost-api#23]
As best I can tell, the `UserProfile` data type is not needed and all API calls having to do with users should use `User` instead. Due to #22 I haven't been able to verify this experimentally, but the API docs suggest this is the case because they do not distinguish between "users" and "user profiles."

**Comment by dagit** [comment]
It's hard to remember now why they both exist, but I think it's because experimentally I was getting different fields and they had different API endpoints.  With those two things combined I think I just assumed they were different types. I think the `User` type has more fields because we use it for the currently logged in user and `UserProfile` is when we just have some data about that other user?

I don't see a problem with merging them, but we'll probably need to change some fields to `Maybe`.

**Comment by aisamanra** [comment]
It looks like there's a vaguely corresponding distinction in the MatterMost source code: there's a `User` type [here](https://github.com/mattermost/platform/blob/master/model/user.go#L42) but also a `UserPatch` [here](https://github.com/mattermost/platform/blob/master/model/user.go#L70) and the latter corresponds vaguely to our `UserProfile` (mostly?) On the other hand, `UserP{atch,rofile}` appears to be a strict subset of `User`, so this would probably be a kosher change.

**Comment by jtdaugherty** [comment]
My proposal is based on two observations: the mattermost API docs do not make a distinction (in fact the word "profile" is not used at all), and the API endpoints that we currently support that distinguish between `User` and `UserProfile` actually return the same data if you look at the API documentation. So I suspect that, as Jason mentioned, this is more a reverse-engineering accident than anything.
